name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CUSTOM_DOMAIN: laptopzonelb.store
  # si tu avais déjà un build configuré pour un sous-chemin de repo (ex: /LaptopZoneLB/)
  # mets-le ici pour réécriture automatique ; sinon laisse vide:
  OLD_REPO_BASE: /LaptopZoneLB/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # --- Safety net : remet les liens d'assets à la racine si un ancien base path traîne ---
      - name: Normalize asset base to root
        run: |
          if [ -n "${OLD_REPO_BASE}" ] && grep -q "${OLD_REPO_BASE}" dist/index.html; then
            echo "Found ${OLD_REPO_BASE} in HTML. Normalizing to root '/'."
            find dist -type f -name "*.html" -print0 | xargs -0 sed -i "s|${OLD_REPO_BASE}|/|g"
          else
            echo "No old repo base found. Skipping normalization."
          fi

      - name: Add CNAME, 404.html, .nojekyll
        run: |
          echo "${CUSTOM_DOMAIN}" > dist/CNAME
          cp dist/index.html dist/404.html
          touch dist/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
